Pr template
octopus12176/hc_practice pull request #2
Opened 2023-08-02 08:53 UTC by octopus12176

## 課題のリンク

-https://octopus12176.github.io/hc_practice/html_css_output_beginner/index.html

## やったこと

- HTML/CSS初級アウトプット課題の作成

## 動作確認方法

- 「課題のリンク」に添付されているURLを開いていただけると確認可能です。

## その他

- 特にございません。

2023-08-03 08:31 UTC, ihatov08 requested changes
![HTML-CSS初級アウトプット課題 (1)](https://github.com/octopus12176/hc_practice/assets/14024165/5078741e-a139-4119-a5dd-10db6efac224)

スマホ表示が崩れているので修正お願いします 🙇

2023-08-04 01:01 UTC, octopus12176 commented
スマホ表示の崩れを修正しましたのでご確認のほどよろしくお願いいたします！

2023-08-04 05:49 UTC, ihatov08 requested changes
スマホで横スクロールができてしまうので、修正お願いします！

2023-08-05 18:11 UTC, octopus12176 commented
@ihatov08 
ご指摘いただいたスマホで横スクロールできてしまうバグを修正しましたのでご確認ほどよろしくお願いいたします！！

2023-08-05 21:46 UTC, ihatov08 approved these changes
確認しました、LGTMです！

2023-08-06 02:59 UTC, octopus12176 commented
@ihatov08 
ありがとうございます！！

2023-08-06 03:00 UTC, merged